import React, { useEffect, useMemo, useState } from 'react';
import DashboardLayout from '@/components/DashboardLayout';
import { useAuth } from '@/context/AuthContext';
import { useToast } from '@/components/ui/use-toast';
import { Gavel, Search, ShieldCheck } from 'lucide-react';
import { supabase } from '@/lib/supabaseClient';

const AnnulmentMatrimonialPage = () => {
  const { user } = useAuth(); const { toast } = useToast(); const [rows,setRows]=useState([]); const [search,setSearch]=useState('');
  useEffect(()=>{if(!user?.parishId)return; (async()=>{const {data,error}=await supabase.from('decretos').select('id,decree_number,decree_date,status,payload,original_record_id,created_at').eq('parish_id',user.parishId).eq('tipo','nulidad_matrimonial').order('created_at',{ascending:false}); if(error)throw error; setRows(data||[]);})().catch(e=>toast({title:'Nulidad matrimonial',description:e.message,variant:'destructive'}));},[user,toast]);
  const filtered=useMemo(()=>{const t=search.toLowerCase(); return rows.filter(r=>`${r.decree_number||''} ${r.payload?.targetName||''} ${r.payload?.reason||''}`.toLowerCase().includes(t));},[rows,search]);
  return <DashboardLayout entityName={user?.parishName||'Parroquia'}><div className="max-w-6xl mx-auto pb-24 pt-6"><div className="flex items-center gap-4 mb-8"><div className="w-14 h-14 rounded-2xl bg-rose-950 text-white flex items-center justify-center"><Gavel/></div><div><h1 className="text-3xl font-black font-serif">Nulidad Matrimonial</h1><p className="text-gray-500">Archivo de sentencias y decretos recibidos de Cancillería. La parroquia consulta; no declara nulidades.</p></div></div><div className="bg-blue-50 border border-blue-100 rounded-2xl p-4 mb-6 flex gap-3"><ShieldCheck className="w-5 h-5 text-blue-700 shrink-0"/><p className="text-sm text-blue-900">Las partidas matrimoniales permanecen en el libro. La sentencia de nulidad se conserva como acto jurídico y genera su nota marginal y auditoría.</p></div><div className="bg-white rounded-2xl border shadow-sm"><div className="p-4 border-b relative"><Search className="absolute left-7 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400"/><input className="w-full pl-10 pr-4 py-3 border rounded-xl font-bold uppercase" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar decreto, nombres o fundamento"/></div>{filtered.length===0?<div className="p-16 text-center text-gray-400">No hay sentencias/decretos de nulidad registrados para esta parroquia.</div>:<div className="divide-y">{filtered.map(r=><div key={r.id} className="p-5"><div className="flex flex-col md:flex-row md:items-center justify-between gap-3"><div><p className="font-mono font-black text-rose-800">#{r.decree_number||r.payload?.decreeNumber}</p><p className="font-black uppercase mt-1">{r.payload?.targetName||'Partida matrimonial'}</p><p className="text-sm text-gray-500 mt-1">Fecha: {r.decree_date||r.payload?.decreeDate||'---'}</p></div><span className="bg-rose-50 text-rose-800 border border-rose-100 rounded-full px-3 py-1 text-[9px] font-black uppercase">{r.status||'active'}</span></div>{r.payload?.reason&&<p className="mt-3 text-sm bg-gray-50 p-3 rounded-xl uppercase">{r.payload.reason}</p>}</div>)}</div>}</div></div></DashboardLayout>;
};
export default AnnulmentMatrimonialPage;
